denoising_net: resnet
hidden_dim: 64
dropout_prob: 0 
n_blocks: 3
embedding_dim: 100
conditional: True
normalization: none
multimodal: False
is_binarized: False
embed_size_factor: False
conditioning_probability: 0.8
guided_conditioning: True