# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu_all
    qos: phd
    cpus_per_task: 6
    mem_gb: 90
    gres: gpu:1
    timeout_min: 1440
    array_parallelism: 4 # max num of tasks to run in parallel (via job array)